version: 2.1

jobs:
  test:
    working_directory: ~/time-tracker
    docker:
      - image: circleci/clojure:lein-2.9.3
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: time_tracker_test
    environment:
      PORT: 8000
      GOOGLE_TOKENINFO_URL: https://www.googleapis.com/oauth2/v3/tokeninfo
      DB_CONNECTION_STRING: jdbc:postgresql://localhost/circle_test?user=ubuntu
      CP_MAX_IDLE_TIME_EXCESS_CONNECTIONS: 1800
      CP_MAX_IDLE_TIME: 10800
      TEST_DB_USERNAME: ubuntu
      GOOGLE_CLIENT_ID: 128416141127-mp9b2fsq6e8bt1r3lva6cot1kdqnlof9.apps.googleusercontent.com
      APP_LOG_LEVEL: debug
      ALLOWED_HOSTED_DOMAIN: "*"
      LOG_FILE_PREFIX: "logs/time-tracker.log"
      NUM_TESTS: 1000
      LOGO: https://nilenso.com/images/nilenso_logos/nilenso_logo.png
    steps:
      - checkout
      - restore_cache:
          key: time-tracker-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: time-tracker-{{ checksum "project.clj" }}
      - run: lein test

workflows:
  build_and_test:
    jobs:
      - test
